#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check for sensitive data
if git diff --cached --name-only | grep -E '\.env\..*$' > /dev/null; then
    echo "Error: Attempting to commit environment files"
    echo "Please remove .env files from staging area"
    exit 1
fi

# Run lint-staged
npx lint-staged